### ISSUE TITLE
Error: Unable to initialize main class com.test.org.MainClass Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/provider/BouncyCastleFipsProvider

### ISSUE THREAD

**Issue by nssssandeep** [kriegaex/JarClassLoader#3]
Hi,

I have made the changes as suggested in the README, but seeing the NoClassDefFoundError. I can see the Jar's got included in jar.

**Comment by kriegaex** [comment]
Please learn [how to ask a question](https://stackoverflow.com/help/how-to-ask) and provide a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve). Then I might reconsider, reopening the issue. Thank you.

You cannot seriously expect me to debug two short sentences of plain prose. In order to achieve that, I would need a magical crystal globe. Please just think like a software developer for a minute and put yourself in my situation. Could you answer me, if I asked you like this? I do not mean to be unkind, I am just trying to guide you towards asking in a way which enables me to help you.
